### ISSUE TITLE
Doesnt work with my PHilipps TV

### ISSUE THREAD

**Issue by OllO18** [Berdsen/telekom-sport-android-tv-unofficial#1]
Thanks for your great work
I installed the apk an my TV .
The app starts but when choosing a live stream it will break.
Any kown issues?
Any Tips?

**Comment by Berdsen** [comment]
Did you login with your account? Without beeing logged in, you can just watch videos, wich are public available (summary of games or Top10 Highlights, etc.).

**Comment by Berdsen** [comment]
Did you get it to work? I will probably add an information dialog, when starting a screen and you're not beeing logged in or not allowed to watch this stream. Perhaps this will help finding an issue.

**Comment by OllO18** [comment]
Yes. I get it work.
Was actually not an issue, just didnt make the setup for the telekom login.
Now it works perfektly.
Thank a lot.

**Comment by Berdsen** [comment]
Fixed with 6081b032631354631eb3d9381ea9e67d595728a9
